---
# tasks file for app
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment"

- name: Install ruby and rubygems and required packages
  apt: "name={{ item }} state=present"
  loop:
    - ruby-full
    - ruby-dev
    - build-essential

- name: Install Ruby bundler
  gem:
    name: bundler
    state: present
    user_install: no

- name: Clone github repo
  git:
    repo: https://github.com/Artemmkin/reddit.git
    dest: "/home/{{ deploy_user }}/reddit"
    version: monolith
    force: yes

- name: Install Bundle
  bundler:
    state: latest
    chdir: "/home/{{ deploy_user }}/reddit"
  notify: Reload_puma

- name: Add puma.service config
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  notify: Reload_puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  notify: Reload_puma

- name: start puma.service
  systemd:
    name: puma.service
    state: started
    enabled: yes
