- name: "Reddit App: Deploy application"  
  hosts: app
  gather_facts: no
  become: true
  vars:
    db_host: 10.132.15.200

  tasks:
  - name: Clone github repo
    git:
      repo: https://github.com/Artemmkin/reddit.git
      dest: /home/appuser/reddit
      version: monolith
      force: yes
 
  - name: Install Bundle
    bundler:
      state: latest
      chdir: /home/appuser/reddit
    notify: Reload_puma

  - name: Copy puma.service config
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    notify: Reload_puma

  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /home/appuser/db_config 
      owner: appuser
      group: appuser
    notify: Reload_puma

  - name: start puma.service
    systemd:
      name: puma.service
      state: started
      enabled: yes

  handlers:
    - name: Reload_puma
      systemd: 
        name: puma
        state: restarted
       
