# Setup and configure ruby things for reddit app
- name: "Reddit App: Configure app environment"
  hosts: all
#  gather_facts: no
  become: yes

  tasks:
  - name: ping
    ping: 
  
  - debug:
      var: ansible_default_ipv4.address

  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    loop:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: no
  become: yes  

  tasks:
  - name: Add apt key for repo
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: EA312927

  - name: Add mongodb repo
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
      filename: mongodb-org-3.2.list
  
  - name: Install mongodb package
    apt:    
      name: mongodb-org
      state: present
      update_cache: yes

  - name: Enable and start mongod service
    systemd:
      name: mongod
      state: started
      enabled: yes

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: reddit_app
  gather_facts: no

  tasks:
  - name: Clone github repo
    git:
      repo: https://github.com/Artemmkin/reddit.git
      dest: /home/appuser/reddit
 
  - name: Install Bundle
    bundler:
      state: latest
      chdir: /home/appuser/reddit

  - name: Copy puma.service config
    become: yes
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service

  - name: start puma.service
    become: true
    systemd:
      name: puma.service
      state: started
      enabled: yes
