# Setup and configure ruby things for reddit app
- name: "Reddit App: Configure app environment"
  hosts: app
  gather_facts: no
  become: true
  tags: app-tag
  tasks:
  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    loop:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: db
  gather_facts: no
  become: true 
  tags: db-tag
  vars:
    mongo_bind_ip: 0.0.0.0
 
  tasks:
  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    notify: Restart_mongod

  - name: Add apt key for repo
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: EA312927

  - name: Add mongodb repo
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present
      filename: mongodb-org-3.2.list
  
  - name: Install mongodb package
    apt:    
      name: mongodb-org
      state: present
      update_cache: yes

  - name: Enable and start mongod service
    systemd:
      name: mongod
      state: started
      enabled: yes
  
  handlers:
  - name: Restart_mongod
    systemd:
      name: mongod
      state: restarted

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: app
  gather_facts: no
  become: true
  tags: deploy-tag
  vars:
    db_host: 10.132.15.198

  tasks:
  - name: Clone github repo
    git:
      repo: https://github.com/Artemmkin/reddit.git
      dest: /home/appuser/reddit
      version: monolith
      force: yes
 
  - name: Install Bundle
    bundler:
      state: latest
      chdir: /home/appuser/reddit
    notify: Reload_puma

  - name: Copy puma.service config
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    notify: Reload_puma

  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /home/appuser/db_config 
      owner: appuser
      group: appuser
    notify: Reload_puma

  - name: start puma.service
    systemd:
      name: puma.service
      state: started
      enabled: yes

  handlers:
    - name: Reload_puma
      systemd: 
        name: puma
        state: restarted
       
